config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'attendances/index'
  get 'attendances/show'
  devise_for :users
  # get 'events/index'
  # get 'events/new'
  # get 'events/show'
  # get 'events/create'
  # get 'events/edit'
  # get 'events/update'
  # get 'events/destroy'
  resources :events
  resources :attendances, only: [:create]

  root 'events#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
# frozen_string_literal: true

class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event
  validates :user_id, uniqueness: { scope: :event_id }
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  validates_presence_of :event_name, :event_date, :event_location, :event_text
  has_many :attendances
  has_many :users, through: :attendances
end

app/models/user.rb
# frozen_string_literal: true
  
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :attendances
  has_many :events
  has_many :events, through: :attendances
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/attendances_controller.rb
# frozen_string_literal: true

class AttendancesController < ApplicationController
  before_action :authenticate_user!
  def index
    @attendances = current_user.attendances
    @events_created = Event.where(user_id: current_user.id)
  end

 

  def create
    @event = Event.find(params[:event_id])
    @attendance = Attendance.new(user: current_user, event: @event)

    if @attendance.save
      flash[:success] = 'You have successfully registered for this event!'
    else
      flash[:error] = 'There was a problem registering for this event.'
    end

    redirect_to @event
  end

  def show
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def show
    @event = Event.find(params[:id])
  end

  def create
    @event = current_user.events.build(event_params)
    @event.user_id = current_user.id
    if @event.save
      # @attendance = Attendance.create(user_id: current_user.id, event_id: @event.id)
      redirect_to events_path(@event)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update; end

  def destroy; end

  private

  def event_params
    params.require(:event).permit(:event_name, :event_date, :event_location, :event_text, :user_id)
  end
  
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/attendances_helper.rb
# frozen_string_literal: true

module AttendancesHelper
end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
end

app/views/attendances/index.html.erb
<style>
  .all-events-container {
    min-width: 340px;
    margin: 0 auto;
    padding: 20px;
    border-radius: 5px;
    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
    margin-bottom: 16px;
    margin-left: 16px;
    margin-right: 16px;
  }

  h1 {
    text-align: center;
    font-size: 28px;
    color: #333;
    margin-bottom: 30px;
  }

  h3 {
    font-size: 20px;
    color: #555;
    margin-bottom: 10px;
  }

  hr {
    border: none;
    border-top: 1px solid #ccc;
    margin: 30px 0;
  }

  h2 {
    font-size: 24px;
    color: #333;
    margin-bottom: 20px;
  }

  p {
    font-size: 16px;
    color: #555;
    margin-bottom: 10px;
  }

  .sign-out-button {
    display: inline-block;
    background-color: tomato;
    color: #fff;
    padding: 10px 20px;
    font-size: 16px;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    transition: background-color 0.3s ease;
  }


</style>

<div class="all-events-container">
  <h1>Attendances#index</h1><br><br>

  <div>
    <h3>User: <%= current_user.email %> </h3>
  </div>

  <hr>

  <div>
    <h2>I made this:</h2>
    <% @events_created.each do |event| %>
      <%= content_tag :p, event.event_name %>
    <% end %>
  </div>

  <hr>

  <div>
    <h2>I will go here:</h2>
    <% @attendances.each do |attendance| %>
      <%= content_tag :p, attendance.event.event_name %>
    <% end %>
  </div><br>

  <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "sign-out-button" %>
</div>

app/views/attendances/show.html.erb
<h1>Attendances#show</h1>
<p>Find me in app/views/attendances/show.html.erb</p>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/edit.html.erb
<h1>Events#edit</h1>
<p>Find me in app/views/events/edit.html.erb</p>

app/views/events/index.html.erb
<div class="all-events-container">
<h3>Events</h3>
 <div class="gridtest">
<% @events.each do |event| %>
<div class="box">
  <div class="container">
    <main class="grid">
      <article>
        <div class="text">
          <h3><%= event.event_name %></h3>
          <h5><%= event.event_location %></h5>
          <p><%= event.event_date %></p>
          <p><%= event.event_text %></p>
          <%= link_to "Show", event_path(event)  %>
        </div>
      </article>
    </main>  
  </div>    
</div>
  <% end %>
</div>

</div>

app/views/events/new.html.erb
<style>
  .new-event {
    max-width: 340px;
    margin: 0 auto;
    padding: 20px;
    border-radius: 5px;
    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
  }

  h2 {
    text-align: center;
    color: #333;
    font-size: 24px;
    margin-bottom: 20px;
  }

  .field {
    margin-bottom: 20px;
  }

  label {
    display: block;
    font-weight: bold;

  }

  input{
    width: 100%;
    padding: 10px;
    font-size: 16px;
    border-radius: 5px;
    border: 1px solid #ccc;
    transition: border-color 0.3s ease;
  }

  input:focus
 {
    border-color: #888;
  }

  .actions {
    text-align: center;
  }

  input[type="submit"] {
    background-color: tomato;
    color: #fff;
    padding: 10px 20px;
    font-size: 16px;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    transition: background-color 0.3s ease;
  }

  input[type="submit"]:hover {
    background-color: #0056b3;
  }

  .error-messages {
    color: #f00;
    font-size: 14px;
    margin-bottom: 10px;
  }

  .links {
    text-align: center;
    margin-top: 20px;
  }

  .links a {
    color: #007bff;
    text-decoration: none;
    font-size: 14px;
    transition: color 0.3s ease;
  }

  .links a:hover {
    color: #0056b3;
  }
</style>

<style>
  .field_with_errors {
    padding: 2px;
    background-color: red;
    display: table;
  }
</style>

<% if @event.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@event.errors.count, "error") %> prohibited this article from being saved:</h2>

    <ul>
      <% @event.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>



<div class="new-event">
  <h2>Creat New Event</h2>

  <%= form_for @event do |f| %>

  <div class="field">
    <%= f.label :event_name, "Event Name:" %><br />
    <%= f.text_field :event_name %>
  </div>

  <div class="field">
    <%= f.label :event_date, "Event Date:" %><br>
    <%= f.datetime_field :event_date, min: Time.now.strftime('%Y-%m-%dT%H:%M') %>
  </div>


  <div class="field">
    <%= f.label :event_location, "Event Location:" %><br>
    <%= f.text_field :event_location %>
  </div>
  <div class="field">
    <%= f.label :event_text, "Event Text:" %><br>
    <%= f.text_area :event_text, style: 'width:100%;' %>
  </div>

  <div class="actions">
    <%= f.submit "Create Event" %>
  </div>
  <% end %>
</div>



<%# Table Event {
  "id" varchar
  "event_name" string
  "event_date" datetime
  "event_location" string
  "event_text" text
  "created_at" datetime
  "updated_at" datetime
} %>

app/views/events/show.html.erb
<style>
  .all-events-container {
    max-width: 800px;
    margin: 0 auto;
    padding: 20px;
    font-family: Arial, sans-serif;
    background-color: #f5f5f5;
    border: 1px solid #ccc;
    border-radius: 5px;
  }

  .event-show-grid {
    display: grid;
    gap: 20px;
  }

  .event-show {
    background-color: #fff;
    padding: 20px;
    border: 1px solid #ccc;
    border-radius: 5px;
  }

  h2 {
    font-size: 24px;
    color: #333;
    margin-bottom: 10px;
  }

  p {
    font-size: 16px;
    color: #555;
    margin-bottom: 10px;
  }

  strong {
    font-weight: bold;
  }

  .attend-button {
    display: inline-block;
    background-color: tomato;
    color: #fff;
    padding: 10px 20px;
    font-size: 16px;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    transition: background-color 0.3s ease;
  }

  .attend-button:hover {
    background-color: #0056b3;
  }

  /* Responsive Styles */
  @media (max-width: 480px) {
    .event-show-grid {
      display: block;
    }

    .event-show {
      margin-bottom: 20px;
    }
  }

  .who-will-go {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 20px;
  }

  .who-will-go-image {
    background-image: url("<%=asset_path"veg-heros.jpg"%>");
    background-size: cover;
    background-position: center;
    color: #fff;
    border-radius: 5px;
  }
</style>

<div class="all-events-container">
  <div class="event-show-grid">
    <div class="event-show">
      <h2>Events#show</h2>

      <p>
        <strong>event_name:</strong>
        <%= @event.event_name %>
      </p>

      <p>
        <strong>event_date:</strong>
        <%= @event.event_date %>
      </p>

      <p>
        <strong>event_location:</strong>
        <%= @event.event_location %>
      </p>

      <p>
        <strong>event_text:</strong>
        <%= @event.event_text %>
      </p>

      <br>
      <%= button_to "I will go", attendances_path(event_id: @event.id), method: :post, class: "attend-button" %>
    </div>

    <div class="who-will-go">
      <div>
        <h2>Who will go</h2>
        <% @event.users.each do |user| %>
          <p><%= user.email %></p>
        <% end %>
      </div>

      <div class="who-will-go-image">
      </div>
    </div>
  </div>
</div>

app/views/events/update.html.erb
<h1>Events#update</h1>
<p>Find me in app/views/events/update.html.erb</p>

app/views/layouts/_footer.html.erb
<div class="footer">
<p>TomatoToe 2023</p>

</div>

app/views/layouts/_header.html.erb
<nav>
<%= link_to root_path do %>
  <div class="svg-logo">
    <ion-icon id="tomato-login" size="large" name="finger-print-outline"></ion-icon>
    <label for="tomato-login">TomatoToe</label>
  </div>
<% end %>

  <div class="nav-menu">
    <li>
      <%= link_to  "Create an event", new_event_path %>
    </li>
       <% if user_signed_in? %>
    <li>
         <%= link_to attendances_index_path do %>
           <%= image_tag 'sett-avatar.png' %>
       <% end %>
    </li>
      <% else %>
          <li><%= link_to  "Log In", new_user_session_path %> </li>
          <li> <%= link_to  "Sign Up", new_user_registration_path %> </li>
      <% end %>
  </div>
</nav>

<div class="hero-image">
<h1>Party Rocking</h1>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Private - Events - App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="alerts">
      <p class="notice"><%#= notice %></p>
      <p class="alert"><%#= alert %></p>
      <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: "alert alert-#{name}" %>
<% end %>

    </div>

    <div class="main">
      <%= yield %>
    </div>
    

    <%= render 'layouts/footer' %>

    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
  </body>
</html>